# Generated by Django 4.0.1 on 2022-01-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwebbot', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='is_corrupt',
            field=models.BooleanField(null=True),
        ),
    ]
