# Generated by Django 4.0.1 on 2022-11-04 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartwebbot', '0003_alter_media_is_corrupt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smartwebbot.media')),
            ],
            bases=('smartwebbot.media',),
        ),
        migrations.CreateModel(
            name='VectorGraphic',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smartwebbot.media')),
            ],
            bases=('smartwebbot.media',),
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
